project:
  type: website

website:
  title: "Rweb"
  navbar:
    left: 
      - text: "Visual Statistics"
        menu: 
          - text: "Two-samples Test"
            href: Two-samples_test.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - united
      - brand
    css: styles.css
    toc: true

editor: visual

